spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/parkingDB
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migrations


cors:
  allowed-origins: "http://localhost:4200"

clients:
  payment:
    url: "https://payment-service"
    timeout:
      connect: 5000
      read: 5000

scheduler:
  parking-closure:
    fixedDelay: 60000
    batchSize: 25