CREATE TABLE IF NOT EXISTS cities (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS parking_zones (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    FOREIGN KEY (city_id) REFERENCES cities(id)
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);